### PR TITLE
API joint for pulsar backend: create,update

### LINKED ISSUE #8: API joint for pulsar backend
We need to make the frontend API caller be compatible with the pulsar backend.

Setup pulsar cluster: https://pulsar.apache.org/docs/en/standalone-docker/ 
API documentation for pulsar function: https://pulsar.apache.org/functions-rest-api/?version=2.7.2&apiversion=v3#tag/functions

The API includes:
- [x] Get List of function
- [x] Get function info
- [ ] Create function
- [ ] Update function
- [x] Delete function
- [x] Get function stats
- [x] Get function status
- [x] Start function
- [x] Stop function

### PR DESCRIPTION
**Pull request by GiorunoGiovanna**
this fix #8

### CODE REVIEW

**Comment by RobertIndie** [comment]
What is the status of this PR? @GiorunoGiovanna

**Comment by GiorunoGiovanna** [comment]
> 
> 
> What is the status of this PR? @GiorunoGiovanna

Now it can create functions, update functions correctly, and refresh after creation

**Comment by GiorunoGiovanna** [comment]
> 
> 
> What is the status of this PR? @GiorunoGiovanna

Now it can create functions, update functions correctly, and refresh after creation

**Review by RobertIndie — CHANGES_REQUESTED** [review]
The update function seems not working. When I update a function and it returns successfully, but the function info does not get updated.

**Review by RobertIndie — COMMENTED** [review]
LGTM

**Pull request merged**
